apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: gitea
  namespace: staging

spec:
  interval: 10m

  chart:
    spec:
      chart: gitea
      version: "11.*"

      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system

  values:
    replicaCount: 1

    ingress:
      enabled: true
      className: traefik

      hosts:
        - host: gitea.staging.local
          paths:
            - path: /
              pathType: Prefix

    postgresql:
      enabled: false

    gitea:
      config:
        database:
          DB_TYPE: postgres
          HOST: gitea-db-rw.staging.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
          PASSWD: gitea-password