apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-secret.yaml
  - postgres-superuser-secret.yaml
  - postgres-cluster.yaml
  - helm-repository.yaml
  - helm-release.yaml